# Generated by Django 4.1.1 on 2022-09-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlname',
            old_name='name',
            new_name='urlName',
        ),
    ]
