# Generated by Django 4.1.1 on 2022-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_urlname_urlname'),
    ]

    operations = [
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
