# Generated by Django 4.1.1 on 2022-09-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='url',
            field=models.URLField(max_length=120),
        ),
    ]
