# Generated by Django 4.1.1 on 2022-09-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_download_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UrlName',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='urlName',
            new_name='url',
        ),
    ]
